grpc:
  server:
    port: 9090
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
        exclude:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8083
